### ISSUE TITLE
error in examples_test.go

### ISSUE THREAD

**Issue by pepelazz** [Shixzie/nlp#1]
Try run function ExampleClassifier_Classify from file 
[examples_test.go](https://github.com/Shixzie/nlp/blob/master/examples_test.go)
and fail with error
```panic: register at least one class before learning```
in place 
```	
        err = cls.Learn()
	if err != nil {
		panic(err)
	}
```

**Comment by Shixzie** [comment]
Thank you, the error was caused because the Classifier func caller wasn't a pointer, it's fixed now, i also updated the Output field to match the design of the NL type. Closing!
