### ISSUE TITLE
extension to allow learning feedback loop at runtime.

### ISSUE THREAD

**Issue by gedw99** [Shixzie/nlp#2]
the current Learn option learns off a fixed set of data if i understand this ?
this is also at design time, which makes sense.

what about at runtime though where we have a HITL (Human in the loop).
With any learning algo, it can be helpful for the NLP to get feedback on how well it is learning from the user. This is more run time learning.
There are lots of subtle ways of getting that positive or negative feedback. 
- if the user immediately pressed the back button after the result was given.
- ask the user with a thumb up or down occasionally.
- maybe some others

This is just an idea i have seen on other machine learning systems. Curious what you think.

**Comment by Shixzie** [comment]
Work is being made to implement this, as well as some performance improvements. Thanks for sharing your ideas! :+1:

**Comment by gedw99** [comment]
Wow that's great.

I will try this out when I get some free time.

I saw another golang g project t that did similar stuff to your. Can't
remember the name :)
But they also designed things so that NLP queries mapped to handlers, like
http of just event handlers.
If you can get a basic example going then it would help me and others use
and contribute.

**Comment by Shixzie** [comment]
It's been so long since I touched this repo, this pkg is meant for pretty straight-forward/simple and predictable grammars, you can achieve more accurate results with machine learning from services like _API.AI_. All efforts on implmenting some kind on machine learning in this pkg have been left apart.
