### ISSUE TITLE
Multiple models ?

### ISSUE THREAD

**Issue by metal3d** [Shixzie/nlp#5]
Hello,
I'm now facing another problem, I wanted to register several models to find many information, here is the problem:

```golang
package main

import (
	"fmt"
	"time"

	"github.com/shixzie/nlp"
)

type Person struct {
	Name string
}

type Job struct {
	Name  string
	Since time.Time
}

func main() {

	nl := nlp.New()
	jobSample := []string{
		"I'm {Name}",
		"I'm {Name} since {Since}",
	}
	persSample := []string{
		"my name is {Name}",
		"call me {Name}",
	}

	err := nl.RegisterModel(Job{}, jobSample, nlp.WithTimeFormat("2006"))
	if err != nil {
		panic(err)
	}
	err = nl.RegisterModel(Person{}, persSample, nlp.WithTimeFormat("2006"))
	if err != nil {
		panic(err)
	}

	err = nl.Learn()
	if err != nil {
		panic(err)
	}

	p := nl.P("Hi, my name is Patrice")
	fmt.Printf("%T, %+v\n", p, p)

	p = nl.P("Hi, I'm engeneer")
	fmt.Printf("%T, %+v\n", p, p)

	p = nl.P("Hi, my name is Patrice and I'm engeneer since 2001")
	fmt.Printf("%T, %+v\n", p, p)
}
```
That sounds ok becaus nl.P() doesn't return a slice. But that cans be problematic if we want to fetch many information to bind them together.

So I have that responses:

```
*main.Person, &{Name:Patrice}
*main.Job, &{Name:engeneer Since:0001-01-01 00:00:00 +0000 UTC}
*main.Job, &{Name:engeneer Since:2001-01-01 00:00:00 +0100 CET}
```

One more time, I will try to find some time to help if I can, but is there any plan to change that kind of behavior ?

**Comment by shixzie** [comment]
You're not being clear enough, you can't say _"here is the problem"_ and attach a code example that works completely fine. If the _goal_ of this issue is to propose something, then please write a new one describing the possible API changes, I've done my best to keep the API the same to not break people's code. Please be more descriptive about what you want to achieve and the possible changes needed for that.

**Comment by metal3d** [comment]
You said: __You're not being clear enough, you can't say "here is the problem" and attach a code example that works completely fine.__

Excuse me but the code is really clear and **doesn't work as expected**: 
I added **2** models, one to get Person and another to get Job with a date. 
The result is that I only have a Job (Why ???) with the sentence "Hi, my name is Patrice and I'm engeneer since 2001" where a Person AND a Job can be found. 

So, I explained that returning an arbitrary type is NOT a good idea. And... just read the following:

You said: __then please write a new one describing the possible API changes__

I said that P() function doesn't return a SLICE, that "sounds ok", but I said "that's problematic to get several types" and bind them together. With a minimum of effort of reflection, you can understand that I expect a way to have several types in return, and not one that is arbitrary ... and reflecting a bit more, you can imagine that an additional function that returns a **slice** is certainly the way to find (to not break existing API).

I could have modified this issue, instead of recreating one, but hey, you decided to attack me I do not know why... and to close the issue without searching to understand, so I'll stop there.

**Comment by shixzie** [comment]
Three things here:

1. In the [Learn](https://github.com/shixzie/nlp#learn-error) section of the readme says: 

> "...using the NaiveBayes algorithm based on those samples..."

If you do some research you will find that similar patterns tend to override others due to the nature of the algorithm, thus giving higher priority to the most-recent ones  (the ones registered the last, aka: `Person` model).

It also says:

> "Learn maps all models samples to their respective models..."

Meaning that since the mapping of `expr -> model` is done by the NaiveBayes algorithm, there's no way of saying _"hey, I've found this Person model, search for others except that one"_.

2. My intent never was to _"attack"_ you, neither I think I _attacked_ you, I just asked you to be descriptive.

> "...Please be more descriptive about what you want to achieve..."

Because decisions should never be made based on assumptions.

3. Workarounds to this limitation:

    * Create one struct that can handle both `Person` and `Job`
    ```go
    type PersonAndJob struct {
        PName string
        JName string
        JSince time.Time
    }
    ```
    * Use better services, here's a quote of me from #2 :
> "...you can achieve more accurate results with machine learning from services like API.AI..."

If the pkg simply doesn't satisfy your needs then search for other solutions, we're developers after all, and finding solutions is what we do the best.

**Comment by metal3d** [comment]
I also developped a Bayesian package in Go that works great and can return as much as categories that the user ask. The only reason I checked your is that you implemented a "keywords system" to get particular entities.

After a read, and some tests, I found a bug (you've resolved) and then I suggest to get "more that one category that matches". So, keep in mind that I spent my time to test.

Why letting "Lean()" method to be called several times if you only return one model ?

> there's no way of saying "hey, I've found this Person model, search for others except that one".

So the problem is here. If you allow to give several models to Learn() method, you may allow to find and returns possible categories (with bayesian value for example). Not only one... Why in  my sentence only the Job is returned, while a Person is also absolutly foundable.

Precision;

> search for others except that one

I never said that, and it's not usefull to remove that model when you fetch other models... Bayesian calculation should give a good result for both.

Follow what I mean: I give a huge text to check, I know that text contains information about places, actors and history. So I give three models to the NRE:

- History
- Place
- Actor

After a call to Learn(), I should have both categories, for example:

```
[evidence: .7, History{Date: 14/07/1789}]
[evidence: .9, Place{Name: "France"}]
[evidence: .6, Actor{Name: "Louis XVI"}]
[evidence: .2, Actor{Name: "Strange name that is not really an actor"}]
```
That's what I make when I want to find, for example, with my implementation, evidence for categories to find in a text.

I worked on recipe extraction (ingredients, cooking methods, weight...) several months ago, with that kind of implementation and I never imaginate to make some strange mixed structures or to return only one found category.
I return every models with calculation results, and I can also ask my function to return only entities that have a result greater than a certain value. Because in a Recipe, I should find severai model at once, not by calling Learn() and P() method for all categories myself. It learn once, and it fetches results for each categories, that's all.

I don't make critics about the fact to ask precision, I could be not as precise as I wanted, but closing an issue and ask to recreate another one instead of leaving me to edit was not very nice.

I never had that reaction if you leaved the issue opened to let me change or make precision after discussion. A simple "excuse me, I don't understand what you want me to add or change" were more appreciable than a "you can't say "here is the problem" and attach a code example that works completely fine" (whitout any "hi", "thanks", or something else that we call "courtesy")
