### ISSUE TITLE
Can you register multiple models for one parser?

### ISSUE THREAD

**Issue by legowerewolf** [Shixzie/nlp#8]
I've tried and all I seem to get out of the parser is the type and model that was registered with the parser first. For example:
```
nl = nlp.New()
checkErr(nl.RegisterModel(ShutdownAction{}, rundata.Samples["shutdown"]))
checkErr(nl.RegisterModel(MuteAction{}, rundata.Samples["mute"]))
nl.Learn()
```
`nl.P()` will *always* return a `ShutdownAction{}`, regardless of whether or not the text fed to `nl.P()` matched any part of the samples provided in `rundata.Samples["shutdown"]`. 

It's not that big of a hardship if I can't, it's just that I would prefer to do it this way and use a type switch than try to use keywords to determine which model I should use to evaluate the input. (I'm working on a chatbot for a Discord server and I'd prefer interactions to be more conversational than having a strict command syntax.

**Comment by shixzie** [comment]
Hi! This behavior may be due to the nature of the Naive Bayes algorithm used to distinguish between models. If the expression is not close enough to any of the models' samples, it will just default to the one passed first.
